### PR TITLE
backports priority pinning

### PR DESCRIPTION
**Pull request by sfuerte**
As per discussion in #10

### CODE REVIEW

**Comment by jnv** [comment]
Thanks for the PR, I think this could work. However, this customization is very Debian-centric. For example Ubuntu's default policy gives backports standard priority of 500 so this can be confusing for other distributions' users. Here're a few points to improve:

- add another variable which turns on the global priority customization (e.g. `backports_priority_enabled`), default false
- rename the file `001_backports` to e.g. `001-ansible-role-debian-backports` so the relation to the role is clear
- add notice to the file that it is maintained by Ansible and should not be manually editable
- as for the default value of priority, you can either keep at 100 or change it to 500 (which would be probably more helpful for Debian users since you can bump up the priority just by switching the boolean flag)

**Comment by sfuerte** [comment]
Hmm, not sure about previous versions of Ubuntu, but got default 100 on 20.04:

```
$ apt-cache policy
Package files:
 100 /var/lib/dpkg/status
     release a=now
 100 http://archive.ubuntu.com/ubuntu focal-backports/universe i386 Packages
     release v=20.04,o=Ubuntu,a=focal-backports,n=focal,l=Ubuntu,c=universe,b=i386
     origin archive.ubuntu.com
...
 500 http://security.ubuntu.com/ubuntu focal-security/universe i386 Packages
     release v=20.04,o=Ubuntu,a=focal-security,n=focal,l=Ubuntu,c=universe,b=i386
     origin security.ubuntu.com
...
 500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
     release v=20.04,o=Ubuntu,a=focal,n=focal,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
```

After the changes:
```
$ apt-cache policy
Package files:
 100 /var/lib/dpkg/status
     release a=now
 600 http://archive.ubuntu.com/ubuntu focal-backports/universe i386 Packages
     release v=20.04,o=Ubuntu,a=focal-backports,n=focal,l=Ubuntu,c=universe,b=i386
     origin archive.ubuntu.com
 600 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages
     release v=20.04,o=Ubuntu,a=focal-backports,n=focal,l=Ubuntu,c=universe,b=amd64
     origin archive.ubuntu.com
...
```

As for the rest, will it shortly.

**Comment by sfuerte** [comment]
Updated as requested

**Comment by sfuerte** [comment]
(@jnv) Jan, do you want me to add/change anything else in the PR?

**Comment by jnv** [comment]
Sorry for leaving you hanging out with this, and thanks for implementing my suggestions! It looks good, I will merge this right away and release it tomorrow.

**Comment by sfuerte** [comment]
Hey,

No worries, busy days/weeks do happen, eh :)  
Thanks a lot for merging.

**Pull request merged**
