### PR TITLE
Add github action for testing with molecule and uri overwriting

### LINKED ISSUE #14: Override of `backports_uri` fails
Thanks for handling of #12, I think the chosen path makes sense.

While trying to override `backports_uri`, to opt-in to use HTTPS on a Debian system, via `group_vars`, I ran into a problem: the override doesn't have any effect.

After looking again into [the docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence), the precedence of `include_vars`, as used in [the code](https://github.com/jnv/ansible-role-debian-backports/blob/master/tasks/main.yml#L3) is higher than most of the other mechanisms to provide variables, including `group_vars`.

Any idea how to deal with this? Is there an alternative we could make use of in this role, to load OS-specific variables, while still keeping the ability to override them?

### PR DESCRIPTION
**Pull request by xshadow**
* This commit adds the molecule testing via github actions
  to this role. This ensures the idempotence and
  continous test of it's functionality. This also
  ensure no current functionality is broken by
  this commit.
* It also sets sane defaults for newer debian versions,
  which means it installs apt-https-transports package
  and uses the https:// backport uri by default
  instead of http://
* This commit allows passing an uri and component variable
  which will superseed the defaults in Ubuntu/Debian.yml
* Closes #14

### CODE REVIEW

**Comment by xshadow** [comment]
You can see the working github actions in my source branch:  https://github.com/xshadow/ansible-role-debian-backports/actions/runs/453320973

**Comment by xshadow** [comment]
I updated my PR, travis-ci is now completely removed, and your tests are done in the verify step by molecule.

**Comment by xshadow** [comment]
Sorry, for the latest change. Needed to be sure that the verify playbooks are also executed in github action docker environment. No more changes incoming. Ready for review.

**Comment by jnv** [comment]
Wow, thanks so much for this, I really appreciate this change! I have a few questions / comments:

- If I understand it correctly, `backports_external_uri` and `backports_external_components` replace `backports_uri` and `backports_components` as a public API. Do you think the logic could be reversed to keep the public API the same? I.e. as an end user I set `backports_uri` and it will override a – hypothetical, distro-specific – `backports_internal_uri` variable. Technically fixing #14 could be considered a breaking change as well, but I would prefer to keep the shorter name of the variable for public API.
- I am still not quite familiar with GitHub actions, but I think the badge's URL is derived from action's name? I.e. `https://github.com/jnv/ansible-role-debian-backports/workflows/Integration/badge.svg?branch=master` won't work if the workflow's name is `Molecule` (you can change the workflow name to Integration or vice versa, I don't mind either option).

Also, perhaps is too much to ask, but could you please split this into two PRs? E.g. keep the Molecule + GitHub Actions + backports_additional_packages in this PR and move fix for #14 to separate PR. This would allow me to put them into separate releases so in case of unexpected regressions or unneeded changes the users can more easily revert to preferred version.

**Comment by xshadow** [comment]
Hey jnv, sure thing. I will do it in seperate PR. 

`backports_external_uri` and `backports_external_components` can be set by people via group_vars or host_vars, since they are no variables which are include in the include files. Those variables will only overwrite the variables `backports_uri/components` if they are set somewhere. By default they will be skipped. 

Nice catch with the workflow name.

**Comment by xshadow** [comment]
Closed in favor for #16

**Pull request closed without merging**
