### PR TITLE
Better defaults (Debian CDN, transport protocol)

### PR DESCRIPTION
**Pull request by nevart**

### CODE REVIEW

**Comment by jnv** [comment]
Hi @nevart, thanks for the PR and sorry for such a late response. In general I would like to accept this, but I have my doubts whether the version comparison is done correctly here. Perhaps it would be safer to use the [version test](https://docs.ansible.com/ansible/2.5/user_guide/playbooks_tests.html#version-comparison)?

**Comment by xshadow** [comment]
@jnv both of the version comparison versions are working:  https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html

**Comment by jnv** [comment]
@xshadow:
> both of the version comparison versions are working: https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html

I am either misunderstanding or missing something. On the page you have linked to they compare exact version numbers, e.g. `ansible_facts['distribution_major_version'] == "6"`. And they do mention greater-than comparison with casting to integer: 
> Tip: Sometimes you’ll get back a variable that’s a string and you’ll want to do a math operation comparison on it. You can do this like so:
> ```
> ...
> when: ansible_facts['os_family'] == "RedHat" and ansible_facts['lsb']['major_release']|int >= 6
> ```

Now my Ansible skills are a bit rusty and I am probably not in touch with the latest development. I assume it works because you can compare strings. But I would prefer to be explicit here, especially when there's a convenient method for that.

**Comment by jnv** [comment]
Okay, I have better, perhaps more radical idea. Assuming from your PR the https is the default since Debian 10 and Ubuntu 18.04. Debian 9 reaches EOL for LT in 2022 and Ubuntu 16.04 next year. I would rather just drop in https as default transport and release it as a breaking change. If you need to support older system, you can either install `apt-transport-https` or set `backports_uri` to use http.

**Comment by jnv** [comment]
(Also, since Debian provides backports only for stable versions, supporting oldstable in this role is irrelevant.)

**Comment by jnv** [comment]
Looks like the Debian has prerequisite for `ca-certificates` to correctly use HTTPS (at least from testing in Docker). Since the defaults in `sources.list` still use http, I will only change Debian defaults to use deb.debian.org and enable https only in Ubuntu.

**Pull request closed without merging**
